telegram_token: '219250835:AAEEvskd7ixSSyRT2jAO-g6HXW7e8ZwKS34'
dadata_url: 'https://suggestions.dadata.ru/suggestions/api/4_1/rs/suggest/%s'
dadata_token: '962ece1f054b4f80f558b93fd4fa635692530c48'
db_name: 'orgs'
db_user_name: 'bot'
db_password: 'vePu4r6AsX8'
db_host: 'localhost'